export { default as Home } from './Home'
export { default as About } from './About'
export { default as Gallery } from './Gallery'
export { default as City } from './City'
export { default as Download } from './Download'
export { default as Footer } from './Footer'
export { default as Nav } from './Nav'