export { default as mage } from '../images/im.png'
export { default as axe } from '../images/axe.png'
export { default as bow } from '../images/bow.png'
export { default as creeper } from '../images/minecraft.png'
export { default as pickaxe } from '../images/pickaxe.png'
export { default as shovel } from '../images/shovel.png'